[package]
name = "zksync_eth_proof_manager"
description = "ZKsync Ethereum proof manager"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
zksync_types.workspace = true
zksync_dal.workspace = true
zksync_config.workspace = true
zksync_contracts.workspace = true
zksync_eth_client.workspace = true
zksync_eth_watch.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
zksync_object_store.workspace = true
zksync_prover_interface.workspace = true
jsonrpsee.workspace = true
zksync_proof_data_handler.workspace = true
zksync_node_fee_model.workspace = true
hex.workspace = true
vise.workspace = true
